* 说明
emacs-eim 的作者似乎已经停止更新eim了，我将eim拼音输入法的相关文件合并到我的emacs配置中，删除了其他输入法，比如：五笔，仓颉等。这个文件是emacs-eim说明文件的缩减版。
* EIM 拼音输入法的特点
Emacs Input Method (EIM) 拼音输入法类似紫光输入法，其特点是：
 1. 自动调频
 2. 自动加入输入的词组。
 3. 不必输入词组的全部拼音，比较智能的查找词组。

在数字后输入标点会不转换成中文标点符号，这是为了方便输入序号和数字。如
果需要作为中文标点符号，再次输入这个标点就好了。可以用

#+BEGIN_SRC org
M-x eim-punc-translate-toggle
#+END_SRC

命令切换输入中英文标点。

* EIM 拼音输入法的安装方式
#+BEGIN_SRC emacs-lisp

(autoload 'eim-use-package "eim" "Another emacs input method")
;; Tooltip 暂时还不好用
(setq eim-use-tooltip nil)

(register-input-method
 "eim-py" "euc-cn" 'eim-use-package
 "拼音" "汉字拼音输入法" "py.txt")

;; 用 ; 暂时输入英文
(require 'eim-extra)
(global-set-key ";" 'eim-insert-ascii)

#+END_SRC

注意，如果所有文件都在 load-path 里的某个目录中，就能找到（如果没有同名
文件的话），否则，请在文件或者配置中使用文件全名。

常用的按键：
|------+----------|
| 按键 | 功能     |
|------+----------|
| C-n  | 向下翻页 |
| C-p  | 向上翻页 |
| C-c  | 取消输入 |
| SPC  | 确定输入 |
| RET  | 字母上屏 |
|------+----------|

按键绑定可以用 C-h I(M-x describe-input-method) 查看。

* 增加自定义词汇
eim默认使用 otherpy.txt 来保存用户自定义词库，我使用~/.emacs.d/eim/pinyin.txt保存我的自定义词库。

可以为eim添加其他输入法的词库，具体方式：
1. 下载其他输入法的词库，比如： 搜狗输入法的细胞词库。
2. 使用 “深蓝词库转换” 转换词库格式（使用自定义输出格式： 类似： “pin|yin 拼音”）。
3. 将生成的文件转码为UTF-8文件。
4. 将文件中的 "|" 替换为："-"。
5. M-x eim-create-word-file 新建一个词库buffer。
6. 将上述文件中的内容粘贴到[table]区。
7. M-x eim-build-table 合并和排序词库。
8. 保存buffer到文件 ~/.emacs.d/eim/pinyin.txt
9. 重新启动emacs。
* 词库merge程序（mergepy.pl）的用法
如果想要更新使用新的拼音词库又不想丢失自己词库里新造的词和词频信息，这时就可以用这个程序。
在命令行中用这样的命令：

#+BEGIN_SRC org
$ perl mergepy.pl 自己的词库文件 新词库文件 -o py-new.txt
#+END_SRC

然后把自己的词库文件备份或者删除，把 py-new.txt 改名成 py.txt 就行了。

* EIM拼音输入法如何增加汉字
在 .emacs 中加上：
#+BEGIN_SRC emacs-lisp
(add-hook 'eim-py-load-hook
	  (lambda ()
	    (eim-py-make-char-table
	     '(("ye" "葉")
	       ("rong" "镕")))))
#+END_SRC
然后在 otherpy.txt 的 [Table] 一行后加上：

#+BEGIN_SRC org
ye 葉
rong 镕
#+END_SRC

#+BEGIN_SRC org
M-x eim-build-table
#+END_SRC

这样应该就能正常使用了。

* 如何使用EIM定制一个输入法
** 初级定制方法：
例如，要设置按键，可以这样：

(add-hook 'eim-py-load-hook
	  (lambda ()
	    (let ((map (eim-mode-map)))
	      (define-key map "-" 'eim-previous-page)
	      (define-key map "=" 'eim-next-page))))

** 高级定制方法：
eim-use-package 可以接受两个参数，一个是 word-file，给出一个词库，一个
是 active-function，这个 active-function 是在每次切换时都要调用的。如果
想只在第一次启动输入法时调用一些命令，最好定义一个变量，在启动之后设置
为 t，或者加入到 eim-load-hook 中。在调用这个命令时，eim-current-package
可能还没有定义（第一次启动），这样，如果要修改或者使用
eim-current-package 中的变量，就要用 eim-load-hook 或者eim-active-hook
或者 eim-active-function。eim-load-hook 只在第一次启动输入法时调
用，eim-active-function 和 eim-active-hook 每次都要调用。一般来说，如果
要修改按键绑定，就加入到 eim-load-hook 中。如果要修改 eim-page-length
这样的局部变量，使用 eim-active-function 或者 eim-active-hook。
eim-active-function 是为有专门的 lib 的输入法设计的，这样不用在
register-input-method 中加入一个 active-function。而 eim-active-hook
是为用户定制设计的，这样不用专门写到一个文件中。设置
eim-active-function 使用eim-set-active-function 函数。

eim-stop-function:
这个函数是用于决定是否停止转换。比如五笔中可以设置当 eim-current-key 大于 4
时就停止。默认是 nil，也就是说可以无限的输入。

eim-translate-function:
当输入的字符是第一个字符（eim-current-key为空）时，如果不在
eim-first-char 中，或者不是第一个字符，但是不在 eim-total-char 中，会
停止转换。这时，会调用这个函数来处理最后一个输入字符。通常用这个函数来
输入标点。

eim-add-completion-function:
通过这个函数来为当前的词条添加更多的选项。当往后翻页超出直接查找到的词
条时，会调用这个函数，如果添加结束，返回 t，还需要再添加返回 nil。
我写的五笔输入法用这个函数时是直接一次性加完。如果要每次添加几个的话，
一种办法就是在 eim-current-choice 中加入一个新元素，记录这次搜索到哪个
位置。下次从这个位置继续，直到结束，比较麻烦。而且，一次加完的速度也很
快，就用简单的办法好了。

eim-format-function:
eim-current-choice 中的第一个元素是通常是一个字符串列表。但是也可以含
有 list。这时需要给出一个显示的函数。比如我在五笔输入法中搜索出可能的
单字或者输入拼音时显示五笔字根。
这个函数要接受四个参数，分别是当前输入的字符串 eim-current-key，
当前页数，所有页数，这一页的选项。

eim-handle-function:
这个函数是决定输入法行为的核心函数。通常要完成的任务是：
1. 决定是否要继续转换。
2. 设置 eim-current-choice, eim-current-pos, eim-current-str,
   eim-guidance-str, 最后调用 eim-show 显示结果。通常如果
   eim-current-choice 的 CAR 不为空的话，就调用 eim-format-page 显示。
   如果为空，则设置相应的 eim-current-str 和 eim-guidance-str，调用
   eim-show 显示。

参考 eim-wb 和 eim-py 的写法。
