#+OPTIONS: H:10 num:t

#+ODT: <text:p text:style-name="PageBreak"/>
* 论文的主体部分

** 论文主体部分的构成
论文主体部分是学位论文的核心部分，其内容可因研究课题性质不同而不同。一般可包括：引言、正文、结论、参考文献等。要求概念清晰，数据可靠，分析严谨，立论正确，要能反映出学位论文的学术水平。

我校的硕士学位论文的正文一般应不少于3万字（图表较多的论文篇幅一般在50页以上），撰写格式应符合本规范中有关格式的规定。

** 引言
引言是论文正文的一个不可分割的组成部分，是正文的先导，是思维活动的诱发。引言的目的是提示内容、启发思路、交待背景、酝酿情绪。

引言的内容应简要说明研究工作的目的、范围、相关领域的前人工作和知识空白、研究设想、研究方法、预期结果和意义等。应言简意赅，但不要与摘要雷同，也不要成为摘要的注释，也应避免出现“自问自答”的讲课形式。

引言应置于“绪论或文献综述”之前单独列出（不加章节号）。有关历史回顾和前人工作的文献综合评论，以及理论分析等，可以在正文中“绪论或文献综述”部分用足够的文字叙述，在引言中不要赘述。对于各章中起始部分对研究背景或内容的简要叙述，可以用小段文字作简略的说明，列于主要内容前，不再使用“引言”、“前言”、“序言”、“概述”等小标题。

** 正文

正文是学位论文的主要部分，应该结构合理，层次清楚，重点突出，文字简练、通顺。

理学、工学的学位论文正文一般包括文献综述、研究内容的总体方案设计及论证、可行性分析、理论分析、实验结果及数据处理分析等。医学类学科的学位论文正文一般包括研究部分、综述部分等；

管理学和文学学科的正文一般包括对研究问题的论述及系统分析、比较研究、模型或方案设计、案例论证或实证分析、模型运行的结果分析或建议、改进措施等。

工程硕士论文（设计）可以是一个完整的工程技术项目的设计或研究课题，可以是技术攻关、技术改造专题，或是新工艺、新设备、新材料、新产品的研制与开发，论文（设计）要有新见解或实用价值（有一定经济效益或社会效益），体现申请人综合运用科学理论、方法和技术手段解决工程实际问题的能力。

由于研究工作涉及的学科、选题、研究方法、工作进程、结果表达方式等有很大的差异，对正文的内容不作统一规定。但必须实事求是，客观真切，准备完备，合乎逻辑，层次分明，简练可读。

** 结论
论文应有结论。论文的结论是最终的、总体的结论，不是正文中各段的小结的简单重复。结论应该观点明确、严谨、完整、准确、精炼。语言文字必须简明扼要。

如果不可能导出应有的结论，也可以没有结论而进行必要的讨论。可以在结论或讨论中提出建议、研究设想、仪器设备改进意见、尚待解决的问题等。

在结论中不要简单重复罗列实验结果，要认真阐明本人在科研工作中创造性的成果和新见解，在本领域中的地位和作用，新见解的意义。对存在的问题和不足应做出客观的叙述。应严格区分自己的成果与他人（特别是导师或导师组的）科研成果的界限。

学位论文的结论应单独作为一章排写，但不加章节号。

** 参考文献
参考文献是文中引用的有具体文字来源的文献集合。我校的硕士学位论文参考文献的数量要求：15年内的参考文献不少于40篇，其中外文参考文献不少于1/3、近5年内的参考文献不少于1/3。

参考文献书写格式的编写依据GB7714—2005《文后参考文献著录规则》中规定：自然科学类论文一般采用顺序编码制，社会科学类论文一般采用著者—出版年制，但不可两种混用。

** 附录
附录是作为论文主体的补充项目，并不是必需的。下列内容可以作为附录编于论文后，也可以另编成册：

1. 为了论文材料的完整，但编入正文又有损于编排的条理和逻辑性，这一类材料包括比正文更为详尽的信息、研究方法和技术更深入的叙述，建议可以阅读的参考文献题录，对了解正文内容有用的补充信息等；
2. 由于篇幅过大或取材于复制品而不便于编入正文的材料；
3. 不便于编入正文的罕见珍贵资料；
4. 对一般读者并非必要阅读，但对于本专业同行有参考价值的资料；
5. 某些重要的原始数据、数学推导、计算程序、框图、结构图、注释、统计表、计算机打印输出件等。

附录一般与论文全文装订在一起，如果附录内容较多时也可独立成册。
#+ODT: <text:p text:style-name="PageBreak"/>
* 书写格式要求
** 论文的章、节、段的编号
根据中华人民和国新闻出版行业标准CY/T 35—2001《科技文献的章节编号方法》的有关规定，论文的章、条、目编号，采用阿拉伯数字分级编号，可向下扩充，各级编号具体格式为“1”、“1.1”、“1.1.1”、“1）”、“（1）”，编号与标题之间加一个空格，如表1所示。

#+CAPTION: 标题排版格式
| 标题                         | 字号字体                             | 格式        | 格式举例       |
|------------------------------+--------------------------------------+-------------+----------------|
| 第一级(章)                   | 三号黑体，英文为“Time New Roman”字体 | 居中，占3行 | 第1章  XXX     |
| 第二级(一级节)               | 四号黑体                             | 居左，占2行 | 1.1 XXXXXX     |
| 第三级(二级节)               | 小四号黑体                           | 居左，占2行 | 1.1.1 XXXXXX   |
| 第四级(根据需要可设置三级节) | 小四号宋体                           | 居左，占2行 | 1.1.1.1 XXXXXX |

论文的附录依序用大写正体A，B，C，...编序号，如：附录A。附录中的图、表、公式、参考文献等另行编序号，与正文分开，也一律用阿拉伯数字编码，但在数码前冠以附录序码，如：图A.1；表B.2；式(B.3)；文献[A.5]等。


注：论文各章之间允许出现不超过一页的空白部分，各章内部页面不能出现空白。

** 篇眉和页码
篇眉从中文摘要开始，奇偶页不同，奇数页内容与该部分的标题相同，偶数页内容为“河北联合大学硕士学位论文”。奇偶页均为“宋体”五号字。

论文页码由引言首页开始一律用阿拉伯数字（- 1 -、- 2 -、- 3 -……）连续的编排。封面、题名页和封底不编入页码。摘要、目次页等前置部分用大写的罗马数字（- I -、- II -）单独编排。页码必须标注在每页的相同位置，便于识别。

** 有关图的规定

图要精选，要具有自明性（即只看图、图例和图题，不阅读正文，就可以理解图意），切忌与表及文字表述重复。图中所用符号应符合国家标准及专业标准，对无规定符号的图形应采用该行业的常用画法。图要清楚，必须确保能复制或微缩。

图包括曲线图、构造图、示意图、图解、框图、纪录图、布置图、地图、照片、图版等。曲线图必须采用封闭框式，不用彩色和灰度来区分不同曲线的标识，图的大小应尽量相同，图的坐标必须标注“量、标准规定符号、单位”，此三者只有在不必要标明（如无量纲等）的情况下方可省略。坐标上标注的量的符号和缩略词必须与正文一致。照片图要求主题和主要显示部分的轮廓鲜明，便于制版。如用放大缩小的复制品，必须清晰反差适中。照片应有表示物尺寸的标度。

图应有编号，图的编号应一直连续到附录之前，图的编号由“图”和从1开始的阿拉伯数字组成，例如“图1”、“图2”等。

图应有图题，图题采用中英文对照，中文在上，英文在下。中文字体用5号黑体，英文字体为五号Times New Ramon字体，且第一个英文单词的首字母大写。图题置于图的编号之后，空一格排写，图的编号和图题置于图下方居中位置。引用图应说明出处，在图题右上角加引用文献号。图中若有分图时，分图号用(a)、(b)等置于分图之下（如图2）。图中各部分说明应采用中文(引用的外文图除外)或数字项号，各项文字说明置于图题之上(有分图题者，置于分图题之上)。有图注或其他说明时应置于图题之上，用5号宋体。范例如图1~图4：

#+CAPTION:

插图编排：图在文中的布局要合理，一般随文编排，先见文字后见图，图与其图题为一个整体，不得拆开排写于两页。插图处的该页空白不够排写该图整体时，可将其后文字部分提前排写，将图移至次页最前面；多图排列时，图与图之间应用足够的空间，上下图之间应用一行的间隔。

注意：文中图最好以嵌入型插入，其与文字的顺序不随文字的增减而变化。

** 有关表的规定
表应有自明性，表的编排时一般是内容和测试项目由左至右横读，数据依序竖读。范例如表2~表3：

表格一律采用“三线表”样式，即表格上下框线、标题行处出现三条贯通的表格线（复合表头中间可以出现非贯通横线），线条宽度为0.5磅，表格中行高的最小值为0.6 mm。表头设计应简单明了，不用斜线。全表如用同一单位，将单位符号放在表题后，加圆括号。表中数据应正确无误，书写清楚。数字空缺的格内加“―”字线（占2个数字），不允许用“''”、“同上”之类的写法。

表应有编号，表的编号由“表”和从1开始的阿拉伯数字组成，例如“表1”、“表2”等，表的编号应一直连续到附录之前，并与章和图的编号无关。

表应有表题，置于表的编号之后。表的编号和表题应置于表上方居中位置。表标题采用中英文对照，中文在上，英文在下。中文字体用5号黑体，英文字体为五号的“Times New Ramon”，且第一个英文单词的首字母大写。

表中的中文字体用5号宋体，英文字体为五号的“Times New Ramon”。

表在文中的布局要合理，表一般随文排，先见文字后见表，如某个表较大而页面篇幅不够时，需要转页接排，在随后的各页上应重复表的编号。编号后跟表题（可省略）和“（续）”，如下所示，续表均应重复表头和关于单位的陈述。多表排列时，上下表之间应有一行间隔。


** 有关符号和缩略词的规定
符号和缩略词应遵循国家标准的有关规定执行，如无标准可循，可采纳本学科或本专业的权威性机构或学术团体所公布的规定；也可以采用全国自然科学名词审定委员会编制的各学科词汇的用词。如不得不引用某些不是公知公用的、且又不易为同行读者所理解的，或系作者自定的符号、记号、缩略词、首字母缩写字等时，均应在第一次出现时一一加以说明，给以明确的定义。

物理量的名称符号应符合国家标准的规定，某量的名称和符号在文中应统一。

物理量计量单位及符号应按国家法定计量单位的标准执行，不得使用非法计量单位及符号。物理量符号、物理常量、变量符号用斜体，计量单位符号一律用正体（一般原则：变量用斜体，常量用正体）。


符号的若干问题
1. 矩阵符号用大写黑斜体字，向量符号用黑斜体字；矩阵转秩符号“T”用白正体字。
2. 物理量、变量、普通集符号用白斜体字。自然数集、实数集、复数集和有理数集分别用黑正体字符N，R，C和Q表示。单位符号用白正体字。
3. 元素符号、化学分子式、数学函数（如、微分符号“d”等）、公用常数（自然对数的底e，圆周率π和虚数单位i（或j）等）均用白正体字。
4. 下标如果是变动的量或表示坐标方向用白斜体。如Xi，i=1,2,3，这里，i是变动的量；或Fx ；这里，x表示坐标。下标如果是表示某种特定含义的单词的字头，则用白正体。
5. 特例：溶液的酸碱度符号为“pH” 用白正体字，此外还有HRC、RH、COD，医学行业特殊符号等。

** 有关计量单位的规定
论文中计量单位必须采用1984年2月27日国务院发布的《中华人民共和国法定计量单位》，并遵照《中华人民共和国法定计量单位使用方法》执行。使用各种量、单位和符号，应遵循国家标准的规定执行。单位名称和符号的书定方式一律采用国际通用符号。论文中使用阿拉伯数字时，其后单位一般采用“单位符号”书写。

我国的法定计量单位（以下简称法定单位）包括：
1. 国际单位制的基本单位（表4）；
2. 国际单位制的辅助单位（表5）；
3. 国际单位制中具有专门名称的导出单位（表6）；
4. 国家选定的非国际单位制单位（表7）；
5. 由以上单位构成的组合形式的单位；
6. 用于构成十进倍数和分数单位的词头（表8）。

#+CAPTION: 国际单位制的基本单位
| 量的名称   | 单位名称     | 单位符号 |
|------------+--------------+----------|
| 长度       | 米           | m        |
| 质量       | 千克（公斤） | kg       |
| 时间       | 秒           | s        |
| 电流       | 安［培］     | A        |
| 热力学温度 | 开［尔文］   | K        |
| 物质的量   | 摩［尔］     | mol      |
| 发光强度   | 坎［德拉］   | cd       |

#+CAPTION: 国际单位制的辅助单位
| 量的名称 | 单位名称 | 单位符号 |
|----------+----------+----------|
| 平面角   | 弧度     | rad      |
| 立体角   | 球面度   | sr       |

#+CAPTION: 国际单位制中具有专门名称的导出单位
| 量的名称               | 单位名称     | 单位符号 | 其他表示式例 |
|------------------------+--------------+----------+--------------|
| 频率                   | 赫［兹］     | Hz       | s-1          |
| 力；重力               | 牛［顿］     | N        | kg·m/s2      |
| 压力，压强；应力       | 帕［斯卡］   | Pa       | N/m2         |
| 能量；功；热           | 焦［耳］     | J        | N·m          |
| 功率；辐射通量         | 瓦［特］     | W        | J/s          |
| 电荷量                 | 库［仑］     | C        | A·s          |
| 电位；电压；电动势     | 伏［特］     | V        | W/A          |
| 电容                   | 法［拉］     | F        | C/V          |
| 电阻                   | 欧［姆］     | Ω        | V/A          |
| 电导                   | 西［门子］   | S        | A/V          |
| 磁通量                 | 韦［伯］     | Wb       | V·s          |
| 磁通量密度，磁感应强度 | 特［斯拉］   | T        | Wb/m2        |
| 电感                   | 亨［利］     | H        | Wb/A         |
| 摄氏温度               | 摄氏度       | ℃        |              |
| 光通量                 | 流明         | lm       | cd·sr        |
| 光照度                 | 勒［克斯］   | lx       | lm/m2        |
| 放射性活度             | 贝可［勒尔］ | Bq       | s-1          |
| 吸收剂量               | 戈［瑞］     | Gy       | J/kg         |
| 剂量当量               | 希［沃特］   | Sv       | J/kg         |

#+ODT: <text:p text:style-name="PageBreak"/>
* 论文的结束部分

** 致谢
致谢是作者对该文章的形成作过贡献的组织或个人予以感谢的文字记载，内容要实在，语言要诚恳、恰当、简短，实事求是，切忌浮夸与庸俗之词。编排在参考文献或附录（若有附录）之后。

一般主要对下列方面致谢：
1. 对科学基金、资助研究工作的奖学金基金、合同单位、资助或支持的企业、组织或个人；
2. 对协助完成研究工作和提供便利条件的组织或个人；
3. 对在研究工作中提出建议和提供帮助的人；
4. 对给予转载和引用权的资料、图片、文献、研究思想和设想的所有者；
5. 对其他应感谢的组织或个人。主要感谢导师和对论文工作有直接贡献及帮助的人士和单位。

注：学位申请人的家属及亲朋好友等与论文无直接关系的人员，一般不列入致谢的范围。切忌抄写师兄的原稿，要注意新信息和自己的文风结合。

** 导师、作者简介
导师简介主要介绍导师的个人信息、学术成果，应言简意赅，主要内容包括姓名、性别、出生年月、民族、出生地；学位、职称；学历、工作经历（职务）；著作与成就；联系方式等，其中涉及导师个人的隐私信息应尽量避免，如果是两个导师指导，两位导师均应进行介绍。

作者简介主要介绍作者的个人信息及在学期间取得的科研成果，主要内容包括姓名、性别、出生年月、民族、出生地；著作与成就等。学术论文研究成果按发表的时间顺序列出，书写格式要求与参考文献相同。研究成果可以是在学期间参加的与学位论文内容相关的学术论文、研究项目、申请的专利或获奖情况等。
#+ODT: <text:p text:style-name="PageBreak"/>
* 论文的打印和装订
我校硕士论文幅面为A4（210×297mm），论文版芯尺寸为（150×227mm）。论文装订时上、下、右边裁去5mm。除封面、题名页、版权页外，论文采用双面印刷。论文封面采用白色铜版纸应用统一格式打印装订。为便于论文的保管和查找，封面应留有书脊，包含论文题目、作者、单位等信息，书脊大小应与论文厚度相称。

在打印前，需要将模版文件中所有提示需要删除的内容全部删除。打印完毕后应仔细检查，特别是字体、字号、行间距等。正文的行间距为1倍行距（模版文件已划分每页32行的网格），中文字体为宋体小四号字，西文字体为Times New Roman 小四号字。其他各项请按照模板文件的相应样式来检查，如有未尽之处请根据具体情况调整，但应使论文整体风格一致。

论文装订前，学位申请人应认真校对，特别是中英文摘要、目录、学科专业名称、参考文献、图表标题号是否与正文一致。

封面、题名页、版权页、中文摘要、英文摘要、目次页、插图或附表清单（可选）、注释说明清单（可选）、引言、正文、结论、参考文献、附录（可选）、致谢、导师简介、作者简介（必须有在学期间的研究成果，硕士研究生在学期间发表的论文必须填于此页）、学位论文数据集。除了上面明确说明可选外，其他各页都必须有，而且格式和装订顺序应当严格按照规范执行。
#+ODT: <text:p text:style-name="PageBreak"/>
